"""Lightweight role-to-keyword lookup for retrieval grounding."""

from __future__ import annotations

ROLE_KEYWORDS: dict[str, list[str]] = {
    "software engineer": [
        "python",
        "javascript",
        "git",
        "api",
        "rest",
        "sql",
        "agile",
        "ci/cd",
        "testing",
        "debugging",
        "object-oriented",
        "data structures",
    ],
    "frontend engineer": [
        "react",
        "typescript",
        "javascript",
        "html5",
        "css3",
        "tailing",
        "next.js",
        "web performance",
        "accessibility",
        "state management",
        "vite",
        "rest api",
    ],
    "backend engineer": [
        "python",
        "node.js",
        "go",
        "sql",
        "postgresql",
        "rest api",
        "graphql",
        "microservices",
        "docker",
        "redis",
        "system design",
        "ci/cd",
    ],
    "full stack engineer": [
        "react",
        "node.js",
        "python",
        "typescript",
        "sql",
        "postgresql",
        "rest api",
        "docker",
        "git",
        "ci/cd",
        "cloud",
        "testing",
    ],
    "data scientist": [
        "python",
        "machine learning",
        "statistics",
        "pandas",
        "numpy",
        "scikit-learn",
        "sql",
        "visualization",
        "jupyter",
        "a/b testing",
        "feature engineering",
        "model evaluation",
    ],
    "data engineer": [
        "python",
        "sql",
        "spark",
        "hadoop",
        "airflow",
        "etl",
        "data warehousing",
        "snowflake",
        "kafka",
        "bigquery",
        "data modeling",
        "dbt",
    ],
    "machine learning engineer": [
        "python",
        "pytorch",
        "tensorflow",
        "machine learning",
        "deep learning",
        "mlops",
        "model deployment",
        "transformers",
        "scikit-learn",
        "cuda",
        "computer vision",
        "nlp",
    ],
    "product manager": [
        "roadmap",
        "stakeholders",
        "user research",
        "kpis",
        "agile",
        "scrum",
        "prioritization",
        "cross-functional",
        "go-to-market",
        "metrics",
        "requirements",
        "backlog",
    ],
    "ux designer": [
        "user research",
        "wireframes",
        "prototypes",
        "figma",
        "usability testing",
        "information architecture",
        "accessibility",
        "design systems",
        "personas",
        "journey mapping",
        "interaction design",
        "visual design",
    ],
    "devops engineer": [
        "kubernetes",
        "docker",
        "terraform",
        "ci/cd",
        "aws",
        "monitoring",
        "linux",
        "ansible",
        "infrastructure as code",
        "jenkins",
        "github actions",
        "incident response",
    ],
    "cloud engineer": [
        "aws",
        "azure",
        "gcp",
        "terraform",
        "docker",
        "kubernetes",
        "networking",
        "iam",
        "cloud security",
        "ci/cd",
        "serverless",
        "cost optimization",
    ],
    "security engineer": [
        "cybersecurity",
        "penetration testing",
        "vulnerability assessment",
        "network security",
        "encryption",
        "iam",
        "siem",
        "incident response",
        "compliance",
        "threat modeling",
        "python",
        "firewalls",
    ],
    "marketing manager": [
        "seo",
        "content strategy",
        "campaigns",
        "analytics",
        "brand",
        "social media",
        "crm",
        "conversion",
        "market research",
        "copywriting",
        "email marketing",
        "roi",
    ],
}


def get_keywords_for_role(role: str) -> list[str]:
    """
    Return curated keywords for a target role.

    Uses exact match first, then partial substring match against known roles.
    Falls back to a generic professional keyword set when no role matches.
    """
    normalized = " ".join(role.lower().split())

    if normalized in ROLE_KEYWORDS:
        return list(ROLE_KEYWORDS[normalized])

    for known_role, keywords in ROLE_KEYWORDS.items():
        if known_role in normalized or normalized in known_role:
            return list(keywords)

    return [
        "communication",
        "collaboration",
        "problem solving",
        "leadership",
        "project management",
        "analytical",
        "results-driven",
        "stakeholder management",
    ]
